export const fooditems = [
    {
      id: 1,
      title: "Diavola Pizza",
      description: "A spicy pizza with organic ingredients and savory salami.",
      sizes: ["Small", "Medium", "Large"],
      image:"/diavola.png",
      tags: ["Organic", "Salami", "Spicy"],
      addons: ["Extra Cheese", "Olives", "Onions", "Mushrooms"],
    },
    {
      id: 2,
      title: "Margherita Pizza",
      description: "A classic pizza with fresh mozzarella and ripe tomatoes.",
      sizes: ["Small", "Medium", "Large"],
      image:"/margherita.png",
      tags: ["Classic", "Mozzarella", "Tomato"],
      addons: ["Basil", "Pepperoni", "Sausage", "Arugula"],
    },
    {
      id: 3,
      title: "Hawaiian Pizza",
      description: "A tropical delight with pineapple, ham, and melted mozzarella.",
      sizes: ["Small", "Medium", "Large"],
      image:"/hawaii.png",
      tags: ["Pineapple", "Ham", "Mozzarella"],
      addons: ["Bacon", "Green Peppers", "Jalapenos", "Red Onions"],
    },
    {
      id: 4,
      title: "Vegetarian Pizza",
      description: "A veggie lover's dream with mushrooms and bell peppers.",
      sizes: ["Small", "Medium", "Large"],
      image:"/vegan.png",
      tags: ["Vegetarian", "Mushrooms", "Bell Peppers"],
      addons: ["Artichoke Hearts", "Spinach", "Sun-Dried Tomatoes", "Feta Cheese"],
    },
    {
      id: 5,
      title: "Chicken Club Sandwich",
      description: "A hearty sandwich featuring grilled chicken, crispy bacon, lettuce, and tomato.",
      sizes: ["Regular", "Large"],
      image:"/chicken.png",
      tags: ["Chicken", "Bacon", "Lettuce", "Tomato"],
      addons: ["Avocado", "Swiss Cheese", "Pickles", "Honey Mustard"],
    },
    {
      id: 6,
      title: "Turkey Avocado Sandwich",
      description: "A refreshing sandwich with turkey, creamy avocado, lettuce, and tomato.",
      sizes: ["Regular", "Large"],
      image:"/turkey.png",
      tags: ["Turkey", "Avocado", "Lettuce", "Tomato"],
      addons: ["Bacon", "Cheddar Cheese", "Cranberry Sauce", "Dijon Mustard"],
    },
  ];
